apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: rhdh-argocd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: hello
        image: quay.io/redhatworkshops/welcome-php:latest
        ports:
        - containerPort: 8080
